CREATE DATABASE IF NOT EXISTS authdb;

USE authdb;

CREATE TABLE IF NOT EXISTS authdb.user (
  id BIGINT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (id),
  scan_string VARCHAR(100) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  admin_level TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS authdb.machine_type (
  id BIGINT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (id),
  displayname VARCHAR (100) NOT NULL,
  time1 TIME
);

CREATE TABLE IF NOT EXISTS authdb.machine (
  id BIGINT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (id),
  type BIGINT,
  FOREIGN KEY (type) REFERENCES authdb.machine_type (id) ON DELETE CASCADE,
  displayname VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS authdb.auth (
  id BIGINT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (id),
  user BIGINT NOT NULL,
  FOREIGN KEY (user) REFERENCES authdb.user (id) ON DELETE CASCADE,
  type BIGINT NOT NULL,
  FOREIGN KEY (type) REFERENCES authdb.machine_type (id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS authdb.log (
  starttime TIMESTAMP NOT NULL,
  endtime TIMESTAMP NULL,
  machine VARCHAR(100) NOT NULL,
  user VARCHAR(100) NOT NULL,
  witness VARCHAR(100) NOT NULL
);