package Api.User;

import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

public class UserCreator {
    @NotNull
    @ApiModelProperty(notes = "The string generated by the user scanning comet card")
    private String scanString;

    @NotNull
    @ApiModelProperty(notes = "The name of the user")
    private String name;

    @NotNull
    @ApiModelProperty(notes = "The school email of the user")
    private String email;

    @Min(0)
    @Max(2)
    @ApiModelProperty(notes = "The admin level of the user 0, 1, or 2")
    private int admin_level;

    public UserCreator() {  }

    public UserCreator(String scanString, String name, String email) {
        this.setScanString(scanString);
        this.setEmail(email);
        this.setName(name);
        this.setAdmin_level(0);
    }


    public UserCreator(String scanString, String name, String email, int admin_level) {
        this.setScanString(scanString);
        this.setEmail(email);
        this.setName(name);
        this.setAdmin_level(admin_level);
    }

    public String getScanString() {
        return scanString;
    }

    public void setScanString(String scanString) {
        this.scanString = scanString;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAdmin_level() {
        return admin_level;
    }

    public void setAdmin_level(int admin_level) {
        this.admin_level = admin_level;
    }

    public User toUser(){
        return new User(scanString,name,email,admin_level);
    }
}
