package Api.User;

import Api.Machine.Machine;
import io.swagger.annotations.ApiModelProperty;
import org.springframework.beans.factory.annotation.Value;

import javax.persistence.*;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

@Entity
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @ApiModelProperty(notes = "The auto generated id of an user")
    private Long id;

    @NotNull
    @Column(name = "scan_string", unique=true)
    @ApiModelProperty(notes = "The string generated by the user scanning comet card")
    private String scanString;

    @NotNull
    @ApiModelProperty(notes = "The name of the user")
    private String name;

    @NotNull
    @ApiModelProperty(notes = "The school email of the user")
    private String email;

    @Value("0")
    @Max(2)
    @Min(0)
    @ApiModelProperty(notes = "The admin level of the user 0, 1, or 2")
    private int admin_level;

    public User() {  }

    public User(String scanString, String name, String email) {
        this.setScanString(scanString);
        this.setEmail(email);
        this.setName(name);
        this.setAdmin_level(0);
    }

    public User(Long id, String scanString, String name, String email) {
        this.setId(id);
        this.setScanString(scanString);
        this.setEmail(email);
        this.setName(name);
        this.setAdmin_level(0);
    }

    public User(String scanString, String name, String email, int admin_level) {
        this.setScanString(scanString);
        this.setEmail(email);
        this.setName(name);
        this.setAdmin_level(admin_level);
    }

    public User(Long id, String scanString, String name, String email, int admin_level) {
        this.setId(id);
        this.setScanString(scanString);
        this.setEmail(email);
        this.setName(name);
        this.setAdmin_level(admin_level);
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getScanString() {
        return scanString;
    }

    public void setScanString(String scanString) {
        this.scanString = scanString;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAdmin_level() {
        return admin_level;
    }

    public void setAdmin_level(int admin_level) {
        this.admin_level = admin_level;
    }


    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", scanString='" + scanString + '\'' +
                ", name='" + name + '\'' +
                ", email='" + email + '\'' +
                ", admin_level='" + admin_level + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object obj) {
        return obj != null && obj instanceof User && this.getId().equals(((User) obj).getId());
    }

    @Override
    public int hashCode() {
        return id.intValue();
    }
}
